SELECT DISTINCT B.PTNO, B.SNAME, B.RECEIPTDATE, B.receipttime, B.SEX, B.AGE, A.LABCODE
FROM SLA_LABRESULT A, SLA_LABMASTER B 
WHERE A.SPECIMENNUM = 4023402
AND A.RECEIPTNO = B.RECEIPTNO 
AND A.SPECIMENNUM = B.SPECIMENNUM
AND B.JSTATUS IN ('1','2')
AND (TRIM(A.RESULT) IS NULL OR TRIM(A.RESULT) = '')
ORDER BY A.LABCODE 
    
